site_name: Isaac Blueprints
theme:
  name: material
  custom_dir: overrides
  favicon: tutorials/assets/favicon.png
  icon:
    logo: material/home
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
  - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: ⚓︎
      toc_depth: 3
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      url_download: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
plugins:
  - include-markdown
  - search:
      separator: '[\s\-\.\_\·]+'
  - literate-nav:
      nav_file: navigation.md
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
  - git-authors:
      show_email_address: false
      sort_authors_by: contribution
  - tags:
      enabled: true
      tags: true
      tags_allowed:
        - Beginner friendly
        - Intermediate
        - Advanced
        - Tutorial
        - Video
        - Lua
        - No Lua
        - Sprites
        - XML
        - Repentance
        - Repentance+
        - REPENTOGON
  - redirects:
      redirect_maps:
        'tutorials/miscellaneous/controller_input.md': 'tutorials/general/controller_input.md'
        'tutorials/miscellaneous/making_rooms.md': 'tutorials/general/making_rooms.md'
        'tutorials/miscellaneous/temporary_effects.md': 'tutorials/general/temporary_effects.md'